jsファイルをtsxファイルに書き換えた
q-miyata/Next.js-React-- pull request #1
Opened 2024-05-24 12:18 UTC by q-miyata

とりあえずtsxファイルにした時に出たエラーを潰しました。

2024-05-26 23:29 UTC, q-nishimura requested changes

2024-05-26 23:29 UTC, q-nishimura commented on pages/_app.tsx
> +  function jumpTo(nextMove:any) {
このanyはanyでなくせます。
汎用的な関数（データの変形を行う場合など）で必要なことはありますが、このような実際の動きをする関数だと、多くの場合anyを使う必要は無いです。

2024-05-26 23:29 UTC, q-nishimura commented on pages/_app.tsx
> +  function handleClick(i:number) {
最終的には prettier 等のフォーマッターが自動で行うんですが、`i: number` のようにコロンと型の間にスペースがあるのが基本なのでそうしてください。

2024-05-26 23:29 UTC, q-nishimura commented on pages/_app.tsx
> +import "@/styles/globals.css"; //パスエイリアスが有効でない
paths に入れていけたんではなかったでしたっけ？
問題なさそうならここのコメントと↓の `../~~~` は消して大丈夫です

2024-05-27 01:29 UTC, q-miyata commented on pages/_app.tsx
> +  function jumpTo(nextMove:any) {
<img width="565" alt="スクリーンショット 2024-05-27 10 18 10" src="https://github.com/q-miyata/Next.js-React--/assets/170387308/2190fb3c-e469-4a5f-a66b-544dd665d70b">

anyを消すと怒られます。とりあえず

function jumpTo(nextMove:number):void {
    setCurrentMove(nextMove);
  }
  
  に直しました。

2024-05-27 05:12 UTC, q-nishimura commented on pages/_app.tsx
> +  function jumpTo(nextMove:any) {
むしろnumberが合ってます 👍

2024-05-27 05:13 UTC, merged